#pragma once
// Auto-generated from data/index.html
static const char INDEX_HTML[] PROGMEM =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>SensorNode</title>\n"
"<style>\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{font-family:monospace;font-size:13px;background:#111;color:#ccc;display:flex;flex-direction:column;min-height:100vh}\n"
"header{background:#1a1a2e;padding:10px 16px;display:flex;align-items:center;gap:12px;border-bottom:1px solid #333}\n"
"header h1{font-size:15px;color:#7eb8f7;letter-spacing:1px}\n"
"#devname{color:#aaa;font-size:12px}\n"
"#refresh-btn{margin-left:auto;background:#23395d;color:#7eb8f7;border:1px solid #7eb8f7;padding:3px 10px;cursor:pointer;border-radius:3px}\n"
"#refresh-btn:hover{background:#2d4a7a}\n"
"main{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;padding:12px;flex:1}\n"
"@media(max-width:640px){main{grid-template-columns:1fr}}\n"
"section{background:#1a1a1a;border:1px solid #2a2a2a;border-radius:4px;padding:12px}\n"
"section h2{font-size:11px;color:#7eb8f7;text-transform:uppercase;letter-spacing:1px;margin-bottom:10px;padding-bottom:6px;border-bottom:1px solid #2a2a2a}\n"
".full{grid-column:1/-1}\n"
".stat-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:6px}\n"
".stat{background:#111;border:1px solid #252525;border-radius:3px;padding:6px 8px}\n"
".stat .label{color:#666;font-size:10px;margin-bottom:2px}\n"
".stat .value{color:#e0e0e0;font-size:13px}\n"
".ok{color:#4caf50}\n"
".err{color:#e53935}\n"
".warn{color:#ffa726}\n"
".form-row{display:flex;align-items:center;gap:8px;margin-bottom:6px}\n"
".form-row label{color:#888;width:90px;flex-shrink:0;font-size:11px}\n"
".form-row input[type=number],.form-row input[type=text],.form-row input[type=password]{background:#111;border:1px solid #333;color:#ddd;padding:3px 6px;border-radius:2px}\n"
".form-row input[type=number]{width:70px}\n"
".form-row input[type=text],.form-row input[type=password]{width:180px}\n"
".form-row input[type=checkbox]{width:16px;height:16px;cursor:pointer;accent-color:#7eb8f7}\n"
"textarea{width:100%;background:#111;border:1px solid #333;color:#ddd;padding:6px;border-radius:2px;min-height:120px;resize:vertical;font-family:monospace;font-size:12px}\n"
".btn{background:#23395d;color:#7eb8f7;border:1px solid #7eb8f7;padding:4px 12px;cursor:pointer;border-radius:3px;font-family:monospace;font-size:12px;margin-top:6px}\n"
".btn:hover{background:#2d4a7a}\n"
".btn.danger{color:#e57373;border-color:#e57373;background:#2a1515}\n"
".btn.danger:hover{background:#3a1f1f}\n"
".btn-row{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}\n"
".msg{margin-top:6px;font-size:11px;min-height:14px}\n"
"/* Sensor cards */\n"
".sensor-card{border:1px solid #2a2a2a;border-radius:3px;padding:8px;margin-bottom:8px;background:#141414}\n"
".sensor-card .sc-head{display:flex;align-items:center;gap:8px;margin-bottom:6px}\n"
".sensor-card .sc-type{color:#7eb8f7;font-size:12px;flex:1}\n"
".sensor-card .sc-fields{display:flex;flex-wrap:wrap;gap:8px}\n"
".sensor-card .sc-field{display:flex;align-items:center;gap:4px;font-size:11px;color:#888}\n"
".sensor-card .sc-field input{width:60px;background:#111;border:1px solid #333;color:#ddd;padding:2px 4px;border-radius:2px;font-size:11px}\n"
"/* Log */\n"
"#log{height:240px;overflow-y:auto;background:#0d0d0d;border:1px solid #222;padding:6px;border-radius:2px;display:flex;flex-direction:column}\n"
".log-entry{padding:1px 0;white-space:pre-wrap;word-break:break-all;line-height:1.5}\n"
".log-info{color:#9ecfff}\n"
".log-warn{color:#ffa726}\n"
".log-error{color:#e57373}\n"
".log-debug{color:#666}\n"
".log-ts{color:#444;font-size:11px;margin-right:6px}\n"
".ws-status{font-size:10px;color:#666;margin-bottom:4px}\n"
".ws-ok{color:#4caf50}\n"
".ws-err{color:#e53935}\n"
"/* Drag */\n"
".draggable-section{position:relative}\n"
".draggable-section>h2{cursor:grab;user-select:none}\n"
".draggable-section>h2::before{content:'⠿\\00a0';color:#444}\n"
".dragging{opacity:.4}\n"
".drag-over{outline:1px solid #7eb8f7}\n"
".sec-grip{position:absolute;right:4px;top:0;bottom:0;display:flex;align-items:center;cursor:ew-resize;color:#333;user-select:none;font-size:13px}\n"
".sec-grip:hover{color:#7eb8f7}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>&#9650; SensorNode</h1>\n"
"  <span id=\"devname\"></span>\n"
"  <button id=\"refresh-btn\" onclick=\"loadState()\">Refresh</button>\n"
"</header>\n"
"<main>\n"
"\n"
"  <!-- Status -->\n"
"  <section class=\"full\">\n"
"    <h2>Status</h2>\n"
"    <div class=\"stat-grid\">\n"
"      <div class=\"stat\"><div class=\"label\">Chip ID</div><div class=\"value\" id=\"s-chip\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">WiFi</div><div class=\"value\" id=\"s-wifi\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">MQTT</div><div class=\"value\" id=\"s-mqtt\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">RSSI</div><div class=\"value\" id=\"s-rssi\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Uptime</div><div class=\"value\" id=\"s-uptime\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Active Sensors</div><div class=\"value\" id=\"s-sensors\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Readings</div><div class=\"value\" id=\"s-readings\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Free Heap</div><div class=\"value\" id=\"s-heap\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Sample Num</div><div class=\"value\" id=\"s-sample\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Tele Interval</div><div class=\"value\" id=\"s-tele\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Build</div><div class=\"value\" id=\"s-build\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">Time</div><div class=\"value\" id=\"s-time\">—</div></div>\n"
"      <div class=\"stat\"><div class=\"label\">NTP</div><div class=\"value\" id=\"s-ntp\">—</div></div>\n"
"    </div>\n"
"  </section>\n"
"\n"
"  <!-- WiFi Setup -->\n"
"  <section id=\"wifi-section\" class=\"draggable-section\" draggable=\"true\" style=\"display:none\">\n"
"    <h2>WiFi Setup</h2>\n"
"    <div id=\"wifi-ap-banner\" style=\"display:none;margin-bottom:10px;padding:8px;background:#2a1500;border:1px solid #ffa726;border-radius:3px;color:#ffa726\">\n"
"      &#9888; Running in AP mode &mdash; configure WiFi below to enable MQTT uplink\n"
"    </div>\n"
"    <div style=\"display:flex;flex-wrap:wrap;gap:8px;align-items:flex-start\">\n"
"      <div>\n"
"        <div style=\"font-size:10px;color:#aaa;margin-bottom:2px;text-transform:uppercase\">Primary</div>\n"
"        <div class=\"form-row\"><label>SSID</label><input type=\"text\" id=\"wifi-ssid\" placeholder=\"Network name\"><button class=\"btn\" onclick=\"scanWifi()\" style=\"margin-top:0;margin-left:4px\">Scan</button></div>\n"
"        <div class=\"form-row\"><label>Password</label><input type=\"password\" id=\"wifi-pass\" placeholder=\"leave empty for open\"></div>\n"
"        <div style=\"font-size:10px;color:#aaa;margin:4px 0 2px;text-transform:uppercase\">Backup</div>\n"
"        <div class=\"form-row\"><label>SSID</label><input type=\"text\" id=\"wifi-ssid2\" placeholder=\"Backup network\"></div>\n"
"        <div class=\"form-row\"><label>Password</label><input type=\"password\" id=\"wifi-pass2\" placeholder=\"leave empty for open\"></div>\n"
"        <button class=\"btn\" onclick=\"saveWifi()\">Save &amp; Reboot</button>\n"
"        <div class=\"msg\" id=\"wifi-msg\"></div>\n"
"      </div>\n"
"      <div id=\"wifi-scan-list\" style=\"display:none;flex:1;min-width:200px\">\n"
"        <div style=\"font-size:10px;color:#666;margin-bottom:4px\">Click to select:</div>\n"
"        <div id=\"wifi-nets\" style=\"display:flex;flex-wrap:wrap;gap:4px\"></div>\n"
"      </div>\n"
"    </div>\n"
"  </section>\n"
"\n"
"  <!-- MQTT Config -->\n"
"  <section id=\"mqtt-section\" class=\"draggable-section\" draggable=\"true\">\n"
"    <h2>MQTT Config</h2>\n"
"    <div class=\"form-row\"><label>Broker</label><input type=\"text\" id=\"mqtt-broker\" placeholder=\"hostname or IP\" style=\"width:200px\"></div>\n"
"    <div class=\"form-row\"><label>Port</label><input type=\"number\" id=\"mqtt-port\" min=\"1\" max=\"65535\"></div>\n"
"    <div class=\"form-row\"><label>Topic Prefix</label><input type=\"text\" id=\"mqtt-prefix\" placeholder=\"Sensors/\" style=\"width:140px\"></div>\n"
"    <div class=\"form-row\"><label>TLS / MQTTS</label><input type=\"checkbox\" id=\"mqtt-tls\"></div>\n"
"    <button class=\"btn\" onclick=\"saveMqttConfig()\">Save &amp; Reboot</button>\n"
"    <div class=\"msg\" id=\"mqtt-msg\"></div>\n"
"  </section>\n"
"\n"
"  <!-- Hardware Setup -->\n"
"  <section id=\"hw-section\" class=\"draggable-section\" draggable=\"true\">\n"
"    <h2>Hardware Setup</h2>\n"
"    <div class=\"form-row\"><label>I2C SDA</label><input type=\"number\" id=\"hw-sda\" min=\"-1\" max=\"48\"></div>\n"
"    <div class=\"form-row\"><label>I2C SCL</label><input type=\"number\" id=\"hw-scl\" min=\"-1\" max=\"48\"></div>\n"
"    <div class=\"form-row\"><label>UART RX</label><input type=\"number\" id=\"hw-urx\" min=\"-1\" max=\"48\"></div>\n"
"    <div class=\"form-row\"><label>UART TX</label><input type=\"number\" id=\"hw-utx\" min=\"-1\" max=\"48\"></div>\n"
"    <div class=\"form-row\"><label>1-Wire pin</label><input type=\"number\" id=\"hw-ow\" min=\"-1\" max=\"48\"></div>\n"
"    <div class=\"form-row\"><label>LED pin</label><input type=\"number\" id=\"hw-led\" min=\"-1\" max=\"48\" title=\"-1 = disabled\"></div>\n"
"    <div class=\"form-row\"><label>Interval (s)</label><input type=\"number\" id=\"hw-interval\" min=\"1\" max=\"3600\"></div>\n"
"    <button class=\"btn\" onclick=\"saveHwConfig()\">Save &amp; Reboot</button>\n"
"    <div class=\"msg\" id=\"hw-msg\"></div>\n"
"  </section>\n"
"\n"
"  <!-- Sensor Setup -->\n"
"  <section id=\"sensorsetup-section\" class=\"draggable-section\" draggable=\"true\">\n"
"    <h2>Sensor Setup</h2>\n"
"    <div id=\"sensor-cards\"></div>\n"
"    <button class=\"btn\" onclick=\"saveSensorSetup()\">Save</button>\n"
"    <div class=\"msg\" id=\"sensorsetup-msg\"></div>\n"
"  </section>\n"
"\n"
"  <!-- Sensor Labels -->\n"
"  <section id=\"sensorlabel-section\" class=\"draggable-section\" draggable=\"true\">\n"
"    <h2>Sensor Labels</h2>\n"
"    <textarea id=\"sensor-json\" spellcheck=\"false\" placeholder=\"Loading...\"></textarea>\n"
"    <div class=\"btn-row\">\n"
"      <button class=\"btn\" onclick=\"saveSensorLabels()\">Save</button>\n"
"      <button class=\"btn\" onclick=\"loadSensorLabels()\">Reload</button>\n"
"    </div>\n"
"    <div class=\"msg\" id=\"sensorlabel-msg\"></div>\n"
"  </section>\n"
"\n"
"  <!-- Commands -->\n"
"  <section id=\"cmd-section\" class=\"draggable-section\" draggable=\"true\">\n"
"    <h2>Commands</h2>\n"
"    <div class=\"btn-row\">\n"
"      <button class=\"btn danger\" onclick=\"sendCmd({cmd:'reboot'})\">Reboot</button>\n"
"      <button class=\"btn\" onclick=\"sendCmd({cmd:'telemetry'})\">Send Telemetry</button>\n"
"      <button class=\"btn\" id=\"debug-btn\" onclick=\"toggleDebug()\">Debug Log: OFF</button>\n"
"    </div>\n"
"    <div class=\"msg\" id=\"cmd-msg\"></div>\n"
"  </section>\n"
"\n"
"  <!-- Firmware Update -->\n"
"  <section id=\"ota-section\" class=\"full draggable-section\" draggable=\"true\">\n"
"    <h2>Firmware Update</h2>\n"
"    <div style=\"display:flex;align-items:center;gap:8px\">\n"
"      <input type=\"file\" id=\"ota-file\" accept=\".bin\" style=\"font-size:12px;font-family:monospace;color:#ccc;background:none;border:none;padding:0;flex:1;min-width:0\">\n"
"      <button class=\"btn\" onclick=\"doOta()\" style=\"margin-top:0;flex-shrink:0\">Flash &amp; Reboot</button>\n"
"    </div>\n"
"    <div style=\"display:flex;align-items:center;gap:8px;margin-top:8px\">\n"
"      <span style=\"flex:1;font-size:12px;color:#888\">Download from OTA server — watch log for progress</span>\n"
"      <button class=\"btn\" onclick=\"postJson('/api/cmd',{cmd:'otaCheck'},'ota-msg')\" style=\"margin-top:0;flex-shrink:0\">Check OTA Server</button>\n"
"    </div>\n"
"    <progress id=\"ota-progress\" value=\"0\" max=\"100\" style=\"width:100%;height:6px;display:none;margin-top:6px\"></progress>\n"
"    <div class=\"msg\" id=\"ota-msg\"></div>\n"
"  </section>\n"
"\n"
"  <!-- Log Stream -->\n"
"  <section id=\"log-section\" class=\"full\">\n"
"    <h2>Log Stream</h2>\n"
"    <div class=\"ws-status\"><span id=\"ws-dot\">&#9679;</span> <span id=\"ws-label\">disconnected</span></div>\n"
"    <div id=\"log\"></div>\n"
"  </section>\n"
"\n"
"</main>\n"
"<script>\n"
"var MAX_LOG = 200;\n"
"\n"
"// ── State ──────────────────────────────────────────────────────────────────────\n"
"function loadState() {\n"
"  fetch('/api/state')\n"
"    .then(function(r){return r.json()})\n"
"    .then(function(d){\n"
"      set('s-chip',   d.chipId);\n"
"      set('s-wifi',   d.apMode ? '<span class=\"warn\">&#9679; AP mode</span>'\n"
"                               : (d.wifiConnected ? '<span class=\"ok\">&#9679; connected</span>'\n"
"                                                  : '<span class=\"err\">&#9679; offline</span>'));\n"
"      set('s-mqtt',   d.mqttConnected ? '<span class=\"ok\">&#9679; connected</span>' : '<span class=\"err\">&#9679; offline</span>');\n"
"      set('s-rssi',   d.apMode ? '—' : (d.wifiRSSI + ' dBm'));\n"
"      set('s-uptime', d.uptime + ' min');\n"
"      set('s-sensors', d.sensorsActive);\n"
"      set('s-readings', d.readingCount);\n"
"      set('s-heap',   Math.round(d.freeHeap/1024) + ' KB');\n"
"      set('s-sample', d.sampleNum);\n"
"      set('s-tele',   d.teleInterval + ' min');\n"
"      set('s-build',  d.build);\n"
"      document.getElementById('devname').textContent = d.sysname || '';\n"
"      if (d.ntpSynced && d.epochTime) {\n"
"        var dt = new Date(d.epochTime*1000);\n"
"        set('s-time', pad(dt.getHours())+':'+pad(dt.getMinutes())+':'+pad(dt.getSeconds()));\n"
"        set('s-ntp',  '<span class=\"ok\">synced</span>');\n"
"      } else {\n"
"        set('s-time', '—');\n"
"        set('s-ntp',  '<span class=\"err\">not synced</span>');\n"
"      }\n"
"    })\n"
"    .catch(function(){set('s-wifi','<span class=\"err\">fetch failed</span>')});\n"
"}\n"
"\n"
"function set(id, html) {\n"
"  var el = document.getElementById(id);\n"
"  if (el) el.innerHTML = html;\n"
"}\n"
"\n"
"// ── WiFi ──────────────────────────────────────────────────────────────────────\n"
"function loadWifi() {\n"
"  fetch('/api/wifi').then(function(r){return r.json()}).then(function(d){\n"
"    document.getElementById('wifi-section').style.display = 'block';\n"
"    document.getElementById('wifi-ap-banner').style.display = d.apMode ? 'block' : 'none';\n"
"    if (d.ssid)  document.getElementById('wifi-ssid').value  = d.ssid;\n"
"    if (d.ssid2) document.getElementById('wifi-ssid2').value = d.ssid2;\n"
"  }).catch(function(){});\n"
"}\n"
"\n"
"function scanWifi() {\n"
"  showMsg('wifi-msg','Scanning...',true);\n"
"  document.getElementById('wifi-scan-list').style.display = 'none';\n"
"  fetch('/api/wifi/scan').then(function(r){return r.json()}).then(function(nets){\n"
"    var c = document.getElementById('wifi-nets');\n"
"    c.innerHTML = '';\n"
"    nets.sort(function(a,b){return b.rssi-a.rssi}).forEach(function(n){\n"
"      var b = document.createElement('button');\n"
"      b.className = 'btn'; b.style.margin = '0';\n"
"      b.textContent = n.ssid+' ('+n.rssi+' dBm'+(n.secure?' \\uD83D\\uDD12':'')+')';\n"
"      b.onclick = function(){ document.getElementById('wifi-ssid').value=n.ssid; document.getElementById('wifi-pass').focus(); };\n"
"      c.appendChild(b);\n"
"    });\n"
"    document.getElementById('wifi-scan-list').style.display = nets.length ? 'block' : 'none';\n"
"    showMsg('wifi-msg', nets.length+' networks found', true);\n"
"  }).catch(function(){showMsg('wifi-msg','Scan failed',false)});\n"
"}\n"
"\n"
"function saveWifi() {\n"
"  var ssid = document.getElementById('wifi-ssid').value.trim();\n"
"  if (!ssid) { showMsg('wifi-msg','SSID required',false); return; }\n"
"  fetch('/api/wifi', {method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({ssid:ssid, pass:document.getElementById('wifi-pass').value,\n"
"      ssid2:document.getElementById('wifi-ssid2').value.trim(),\n"
"      pass2:document.getElementById('wifi-pass2').value})\n"
"  }).then(function(r){return r.json()}).then(function(d){showMsg('wifi-msg',d.ok?(d.msg||'OK'):('Error: '+d.error),d.ok)})\n"
"    .catch(function(){showMsg('wifi-msg','Request failed',false)});\n"
"}\n"
"\n"
"// ── MQTT Config ────────────────────────────────────────────────────────────────\n"
"function loadMqttConfig() {\n"
"  fetch('/api/mqtt/config').then(function(r){return r.json()}).then(function(d){\n"
"    document.getElementById('mqtt-broker').value = d.broker || '';\n"
"    document.getElementById('mqtt-port').value   = d.port   || 8883;\n"
"    document.getElementById('mqtt-prefix').value = d.prefix || 'Sensors/';\n"
"    document.getElementById('mqtt-tls').checked  = !!d.tls;\n"
"  }).catch(function(){});\n"
"}\n"
"\n"
"function saveMqttConfig() {\n"
"  var body = {\n"
"    broker: document.getElementById('mqtt-broker').value.trim(),\n"
"    port:   parseInt(document.getElementById('mqtt-port').value),\n"
"    prefix: document.getElementById('mqtt-prefix').value,\n"
"    tls:    document.getElementById('mqtt-tls').checked\n"
"  };\n"
"  if (!body.broker) { showMsg('mqtt-msg','Broker required',false); return; }\n"
"  fetch('/api/mqtt/config', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)})\n"
"    .then(function(r){return r.json()})\n"
"    .then(function(d){ showMsg('mqtt-msg', d.ok ? (d.msg||'Saved — rebooting') : ('Error: '+d.error), d.ok); })\n"
"    .catch(function(){showMsg('mqtt-msg','Request failed',false)});\n"
"}\n"
"\n"
"// ── Hardware Setup ─────────────────────────────────────────────────────────────\n"
"function loadHwConfig() {\n"
"  fetch('/api/hw/config').then(function(r){return r.json()}).then(function(d){\n"
"    document.getElementById('hw-sda').value      = d.i2c_sda  !== undefined ? d.i2c_sda  : 4;\n"
"    document.getElementById('hw-scl').value      = d.i2c_scl  !== undefined ? d.i2c_scl  : 5;\n"
"    document.getElementById('hw-urx').value      = d.uart_rx  !== undefined ? d.uart_rx  : 13;\n"
"    document.getElementById('hw-utx').value      = d.uart_tx  !== undefined ? d.uart_tx  : 15;\n"
"    document.getElementById('hw-ow').value       = d.onewire  !== undefined ? d.onewire  : 2;\n"
"    document.getElementById('hw-led').value      = d.led_pin  !== undefined ? d.led_pin  : -1;\n"
"    document.getElementById('hw-interval').value = d.interval !== undefined ? d.interval : 60;\n"
"  }).catch(function(){});\n"
"}\n"
"\n"
"function saveHwConfig() {\n"
"  var body = {\n"
"    i2c_sda:  parseInt(document.getElementById('hw-sda').value),\n"
"    i2c_scl:  parseInt(document.getElementById('hw-scl').value),\n"
"    uart_rx:  parseInt(document.getElementById('hw-urx').value),\n"
"    uart_tx:  parseInt(document.getElementById('hw-utx').value),\n"
"    onewire:  parseInt(document.getElementById('hw-ow').value),\n"
"    led_pin:  parseInt(document.getElementById('hw-led').value),\n"
"    interval: parseInt(document.getElementById('hw-interval').value)\n"
"  };\n"
"  fetch('/api/hw/config', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)})\n"
"    .then(function(r){return r.json()})\n"
"    .then(function(d){ showMsg('hw-msg', d.ok ? (d.msg||'Saved — rebooting') : ('Error: '+d.error), d.ok); })\n"
"    .catch(function(){showMsg('hw-msg','Request failed',false)});\n"
"}\n"
"\n"
"// ── Sensor Setup ───────────────────────────────────────────────────────────────\n"
"var SENSOR_TYPES = [\n"
"  {type:'bme280',  label:'BME280',      fields:[{key:'addr',label:'I2C addr',def:0x76}]},\n"
"  {type:'sht30',   label:'SHT30/SHT31', fields:[{key:'addr',label:'I2C addr',def:0x44}]},\n"
"  {type:'ds18b20', label:'DS18B20',     fields:[]},\n"
"];\n"
"\n"
"var sensorSetupData = [];\n"
"\n"
"function renderSensorCards(data) {\n"
"  var container = document.getElementById('sensor-cards');\n"
"  container.innerHTML = '';\n"
"  SENSOR_TYPES.forEach(function(st) {\n"
"    var entry = data.find(function(e){return e.type===st.type}) || {type:st.type,enabled:false};\n"
"    var card = document.createElement('div');\n"
"    card.className = 'sensor-card';\n"
"    var headHtml = '<div class=\"sc-head\">'\n"
"      +'<input type=\"checkbox\" data-type=\"'+st.type+'\" '+(entry.enabled?'checked':'')+'>'\n"
"      +'<span class=\"sc-type\">'+st.label+'</span></div>';\n"
"    var fieldsHtml = '<div class=\"sc-fields\">';\n"
"    st.fields.forEach(function(f){\n"
"      var val = entry[f.key] !== undefined ? entry[f.key] : f.def;\n"
"      fieldsHtml += '<div class=\"sc-field\"><span>'+f.label+'</span>'\n"
"        +'<input type=\"number\" data-type=\"'+st.type+'\" data-key=\"'+f.key+'\" value=\"'+val+'\"></div>';\n"
"    });\n"
"    fieldsHtml += '</div>';\n"
"    card.innerHTML = headHtml + fieldsHtml;\n"
"    container.appendChild(card);\n"
"  });\n"
"}\n"
"\n"
"function loadSensorSetup() {\n"
"  fetch('/api/sensors/setup').then(function(r){return r.json()}).then(function(d){\n"
"    sensorSetupData = Array.isArray(d) ? d : [];\n"
"    renderSensorCards(sensorSetupData);\n"
"  }).catch(function(){renderSensorCards([])});\n"
"}\n"
"\n"
"function saveSensorSetup() {\n"
"  var result = [];\n"
"  SENSOR_TYPES.forEach(function(st) {\n"
"    var cb  = document.querySelector('input[type=checkbox][data-type=\"'+st.type+'\"]');\n"
"    var obj = {type: st.type, enabled: cb ? cb.checked : false};\n"
"    st.fields.forEach(function(f){\n"
"      var inp = document.querySelector('input[data-type=\"'+st.type+'\"][data-key=\"'+f.key+'\"]');\n"
"      if (inp) obj[f.key] = parseInt(inp.value);\n"
"    });\n"
"    result.push(obj);\n"
"  });\n"
"  fetch('/api/sensors/setup', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(result)})\n"
"    .then(function(r){return r.json()})\n"
"    .then(function(d){showMsg('sensorsetup-msg', d.ok ? 'Saved.' : ('Error: '+d.error), d.ok)})\n"
"    .catch(function(){showMsg('sensorsetup-msg','Request failed',false)});\n"
"}\n"
"\n"
"// ── Sensor Labels ──────────────────────────────────────────────────────────────\n"
"function loadSensorLabels() {\n"
"  fetch('/api/sensors').then(function(r){return r.json()}).then(function(d){\n"
"    document.getElementById('sensor-json').value = JSON.stringify(d,null,2);\n"
"  }).catch(function(){document.getElementById('sensorlabel-msg').textContent='Fetch failed'});\n"
"}\n"
"\n"
"function saveSensorLabels() {\n"
"  var raw = document.getElementById('sensor-json').value;\n"
"  try { JSON.parse(raw); } catch(e) {\n"
"    document.getElementById('sensorlabel-msg').textContent = 'Invalid JSON: '+e.message; return;\n"
"  }\n"
"  fetch('/api/sensors',{method:'POST',headers:{'Content-Type':'application/json'},body:raw})\n"
"    .then(function(r){return r.json()})\n"
"    .then(function(d){showMsg('sensorlabel-msg', d.ok?'Saved.':('Error: '+d.error), d.ok)})\n"
"    .catch(function(){showMsg('sensorlabel-msg','Request failed',false)});\n"
"}\n"
"\n"
"// ── Commands ───────────────────────────────────────────────────────────────────\n"
"function sendCmd(body) { postJson('/api/cmd', body, 'cmd-msg'); }\n"
"\n"
"var debugOn = false;\n"
"function toggleDebug() {\n"
"  debugOn = !debugOn;\n"
"  postJson('/api/cmd', {debugLog: debugOn}, 'cmd-msg');\n"
"  var btn = document.getElementById('debug-btn');\n"
"  btn.textContent = 'Debug Log: '+(debugOn?'ON':'OFF');\n"
"  btn.style.color = debugOn ? '#4caf50' : '';\n"
"  btn.style.borderColor = debugOn ? '#4caf50' : '';\n"
"}\n"
"\n"
"// ── OTA ────────────────────────────────────────────────────────────────────────\n"
"function doOta() {\n"
"  var file = document.getElementById('ota-file').files[0];\n"
"  if (!file) { showMsg('ota-msg','Select a .bin file first',false); return; }\n"
"  var prog = document.getElementById('ota-progress');\n"
"  prog.value = 0; prog.style.display = 'block';\n"
"  var fd = new FormData();\n"
"  fd.append('firmware', file, file.name);\n"
"  var xhr = new XMLHttpRequest();\n"
"  xhr.upload.onprogress = function(e){ if(e.lengthComputable) prog.value=Math.round(e.loaded/e.total*100); };\n"
"  xhr.onload = function(){\n"
"    prog.value=100;\n"
"    try { var d=JSON.parse(xhr.responseText); showMsg('ota-msg',d.ok?'Flashed — rebooting':('Error: '+d.error),d.ok); }\n"
"    catch(e){ showMsg('ota-msg','Done',true); }\n"
"    prog.style.display = 'none';\n"
"  };\n"
"  xhr.onerror = function(){ showMsg('ota-msg','Upload failed',false); prog.style.display='none'; };\n"
"  xhr.open('POST','/api/ota');\n"
"  xhr.send(fd);\n"
"}\n"
"\n"
"// ── Helpers ────────────────────────────────────────────────────────────────────\n"
"function postJson(url, body, msgId) {\n"
"  fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})\n"
"    .then(function(r){return r.json()})\n"
"    .then(function(d){showMsg(msgId, d.ok?'OK':('Error: '+d.error), d.ok)})\n"
"    .catch(function(){showMsg(msgId,'Request failed',false)});\n"
"}\n"
"\n"
"function showMsg(id, text, ok) {\n"
"  var el = document.getElementById(id);\n"
"  if (!el) return;\n"
"  el.innerHTML = '<span class=\"'+(ok?'ok':'err')+'\">'+text+'</span>';\n"
"  setTimeout(function(){el.textContent='';},3000);\n"
"}\n"
"\n"
"function pad(n){ return n<10?'0'+n:''+n; }\n"
"function escHtml(s){ return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }\n"
"\n"
"// ── WebSocket log ──────────────────────────────────────────────────────────────\n"
"function connectWs() {\n"
"  var wsUrl = 'ws://'+location.hostname+':81';\n"
"  var ws = new WebSocket(wsUrl);\n"
"  var dot = document.getElementById('ws-dot');\n"
"  var lbl = document.getElementById('ws-label');\n"
"  ws.onopen  = function(){ dot.className='ws-ok'; lbl.textContent='connected to '+wsUrl; };\n"
"  ws.onclose = function(){ dot.className='ws-err'; lbl.textContent='disconnected — retrying in 3s'; setTimeout(connectWs,3000); };\n"
"  ws.onerror = function(){ ws.close(); };\n"
"  ws.onmessage = function(evt){\n"
"    var d; try{d=JSON.parse(evt.data);}catch(e){return;}\n"
"    var log = document.getElementById('log');\n"
"    var row = document.createElement('div');\n"
"    row.className = 'log-entry log-'+(d.l||'info');\n"
"    var ts = Math.floor((d.t||0)/1000);\n"
"    var h=Math.floor(ts/3600), m=Math.floor((ts%3600)/60), s=ts%60;\n"
"    row.innerHTML = '<span class=\"log-ts\">'+pad(h)+':'+pad(m)+':'+pad(s)+'</span>'\n"
"                  + '<span class=\"warn\">['+d.l+']</span> '+escHtml(d.m||'');\n"
"    log.appendChild(row);\n"
"    while(log.children.length>MAX_LOG) log.removeChild(log.firstChild);\n"
"    log.scrollTop = log.scrollHeight;\n"
"  };\n"
"}\n"
"\n"
"// ── Init ───────────────────────────────────────────────────────────────────────\n"
"loadState();\n"
"loadWifi();\n"
"loadMqttConfig();\n"
"loadHwConfig();\n"
"loadSensorSetup();\n"
"loadSensorLabels();\n"
"connectWs();\n"
"setInterval(loadState, 15000);\n"
"\n"
"// ── Drag & drop ────────────────────────────────────────────────────────────────\n"
"(function(){\n"
"  var src=null, fromHandle=false;\n"
"  document.addEventListener('mouseup',function(){fromHandle=false;});\n"
"  function ds(e){if(!fromHandle){e.preventDefault();return;}src=this;setTimeout(function(){if(src)src.classList.add('dragging');},0);}\n"
"  function de(){fromHandle=false;this.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(function(x){x.classList.remove('drag-over');});var o=[];document.querySelectorAll('main .draggable-section').forEach(function(x){if(x.id)o.push(x.id);});localStorage.setItem('sOrder',JSON.stringify(o));}\n"
"  function dv(e){e.preventDefault();}\n"
"  function den(e){if(this!==src)this.classList.add('drag-over');}\n"
"  function dl(e){if(!this.contains(e.relatedTarget))this.classList.remove('drag-over');}\n"
"  function dp(e){e.preventDefault();this.classList.remove('drag-over');if(!src||this===src)return;var r=this.getBoundingClientRect();this.parentNode.insertBefore(src,e.clientY<r.top+r.height/2?this:this.nextSibling);}\n"
"  document.querySelectorAll('.draggable-section').forEach(function(el){\n"
"    var h2=el.querySelector('h2');\n"
"    if(h2) h2.addEventListener('mousedown',function(){fromHandle=true;});\n"
"    el.addEventListener('dragstart',ds);el.addEventListener('dragend',de);\n"
"    el.addEventListener('dragover',dv);el.addEventListener('dragenter',den);\n"
"    el.addEventListener('dragleave',dl);el.addEventListener('drop',dp);\n"
"  });\n"
"  var stored=localStorage.getItem('sOrder');\n"
"  if(stored){var anchor=document.getElementById('log-section');try{JSON.parse(stored).forEach(function(id){var el=document.getElementById(id);if(el)anchor.parentNode.insertBefore(el,anchor);});}catch(e){}}\n"
"})();\n"
"\n"
"// ── Section resize ─────────────────────────────────────────────────────────────\n"
"(function(){\n"
"  function getSpan(el){return parseInt(el.getAttribute('data-span')||(el.classList.contains('full')?'3':'1'));}\n"
"  function setSpan(el,n){n=Math.max(1,Math.min(3,n));el.setAttribute('data-span',n);el.style.gridColumn=n>1?'span '+n:'';if(n===3)el.classList.add('full');else el.classList.remove('full');}\n"
"  function saveSpans(){var s={};document.querySelectorAll('.draggable-section').forEach(function(x){if(x.id)s[x.id]=getSpan(x);});localStorage.setItem('sSpans',JSON.stringify(s));}\n"
"  document.querySelectorAll('.draggable-section').forEach(function(el){\n"
"    setSpan(el,getSpan(el));\n"
"    var g=document.createElement('div');g.className='sec-grip';g.textContent='⣿';el.appendChild(g);\n"
"    g.addEventListener('mousedown',function(e){\n"
"      e.stopPropagation();e.preventDefault();\n"
"      var main=document.querySelector('main');\n"
"      var cw=parseFloat(getComputedStyle(main).gridTemplateColumns.split(' ')[0]);\n"
"      var sx=e.clientX,ss=getSpan(el);\n"
"      function mv(e){setSpan(el,ss+Math.round((e.clientX-sx)/(cw+12)));}\n"
"      function up(){document.removeEventListener('mousemove',mv);document.removeEventListener('mouseup',up);saveSpans();}\n"
"      document.addEventListener('mousemove',mv);document.addEventListener('mouseup',up);\n"
"    });\n"
"  });\n"
"  var s=localStorage.getItem('sSpans');\n"
"  if(s){try{var sp=JSON.parse(s);Object.keys(sp).forEach(function(id){var el=document.getElementById(id);if(el)setSpan(el,sp[id]);});}catch(e){}}\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n"
"";
